name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # ex2: this chunk (installing test deps) was missing initially, added after failing pipeline
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          python - <<'PY'
          # EX1: indent is incorrect, give yaml file to chatgpt with the error and ask for a fix          
          import pytest, sys, os, subprocess
          # lightweight: install pytest just-in-time
          subprocess.check_call([sys.executable, "-m", "pip", "install", "pytest"])
          print("Pytest version:", subprocess.check_output([sys.executable, "-m", "pytest", "--version"]).decode())
          sys.exit(subprocess.call([sys.executable, "-m", "pytest", "-q"]))
          PY
